bacit-dotnet.MVC/Models/Suggestions/Suggestions.cs
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection.Metadata;

namespace bacit_dotnet.MVC.Models
{
    // This is the model for Suggestions. Model is the M in MVC
    // The model is like a reflection of the related Db table, in this case the Suggestions Db table.
    // Each variable in the model reflects each column in the Db table.
    
    // Using [DataAnnotations] we can set up client-side validation for each variable/column before sending sending the data to the Db.
    // Even though many of the [DataAnnotations] keywords are useful when using db migrations, we have mainly done all Db edits manually.
    
    // [Key] defines the primary key of the table.
    // [Required] defines that the variable can not be null. By adding (ErrorMessage="") we can also define a custom error message.
    // [Range] defines that the int value must be a value between 1 and ints max possible value.
    // [StringLenght] defines that the string lenght has a maximum and minimum lenght. 
    // [Foreign Key] defines that the variable is a foreign key connected to another table.
    public class Suggestions
    {
        [Key]
        public int SuggestionId { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en ansatt.")]
        [Range(1, int.MaxValue)]
        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "Vennligst fyll inn tittelen.")]
        [StringLength(30,MinimumLength = 2)]
        public string? Title { get; set; }

        [Required(ErrorMessage = "Vennligst fyll inn beskrivelsen.")]
        [StringLength(500, MinimumLength = 2)]
        public string? Description { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;
        
        [Required(ErrorMessage = "Vennligst velg en tidsfrist.")]
        public DateTime Deadline { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en status.")]
        public string? Status { get; set; }

        [Required(ErrorMessage = "Vennligst velg en PDSA-fase.")]
        public string? Phase { get; set; }

        [Required(ErrorMessage = "Vennligst velg en kategori.")]
        public string? Category { get; set; }

        public byte[]? Attachments { get; set; }
        
        public byte[]? AttachmentsAfter { get; set; }
        
        [ForeignKey("teamId")]
        [Required(ErrorMessage = "Vennligst velg et gyldig team.")]
        [Range(1, int.MaxValue)]
        public int TeamId { get; set; }
        
        // a variable that holds a team obj
        public Teams? Team { get; set; }
        
        [ForeignKey("UserId")]
        [Required(ErrorMessage = "Vennligst velg en ansatt.")]
        public int UserId { get; set; }
        
        // a variable that holds a user obj
        public UserEntity? User { get; set; }
        
        // a variable that holds a user obj
        public UserEntity? Employee { get; set; }
    }
}

bacit-dotnet.MVC/ViewModels/Suggestions/CreateSuggestionViewModel.cs
using System.ComponentModel.DataAnnotations;
using bacit_dotnet.MVC.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace bacit_dotnet.MVC.ViewModels

{
    public class CreateSuggestionViewModel
    { 
        public IFormFile? Attachments { get; set; }
        
        public IFormFile? AttchmentsAfter { get; set; }
        
        [ValidateNever]
        public Teams[] Teams { get; set; }
        
        [ValidateNever]
        public UserEntity[] Users { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en ansatt.")]
        [Range(1, int.MaxValue)]
        public int EmployeeId { get; set; }
        
        [Required(ErrorMessage = "Vennligst fyll inn tittelen.")]
        [StringLength(30,MinimumLength = 2)]
        public string? Title { get; set; }
        
        [Required(ErrorMessage = "Vennligst fyll inn beskrivelsen.")]
        [StringLength(500, MinimumLength = 2)]
        public string? Description { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en tidsfrist.")]
        public DateTime? Deadline { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en status.")]
        public string? Status { get; set; }

        [Required(ErrorMessage = "Vennligst velg en PDSA-fase.")]
        public string? Phase { get; set; }

        [Required(ErrorMessage = "Vennligst velg en kategori.")]
        public string? Category { get; set; }

        [Required(ErrorMessage = "Vennligst velg et gyldig team.")]
        [Range(1, int.MaxValue)]
        public int TeamId { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en ansvarsperson.")]
        [Range(1, int.MaxValue)]
        public int UserId { get; set; }
    }
}

bacit-dotnet.MVC/ViewModels/Suggestions/EditSuggestionViewModel.cs
using System.ComponentModel.DataAnnotations;
using bacit_dotnet.MVC.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace bacit_dotnet.MVC.ViewModels;

public class EditSuggestionViewModel
{
    public Teams[]? Teams { get; set; }
    
    public UserEntity[]? Users { get; set; }
    
    [Required]
    public int TeamId { get; set; }
    
    [Required]
    public int UserId { get; set; }

    [Range(1, int.MaxValue)]
    public int SuggestionId { get; set; }
    
    [Range(1, int.MaxValue)]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(30,MinimumLength = 2)]
    public string? Title { get; set; }

    [Required]
    [StringLength(500, MinimumLength = 2)]
    public string? Description { get; set; }
    
    [Required]
    public string? Status { get; set; }

    [Required]
    public string? Phase { get; set; }

    [Required]
    public string? Category { get; set; }

    [Required]
    public DateTime Deadline { get; set; }

    public IFormFile? Attachment { get; set; }
    
    public IFormFile? AttchmentsAfter { get; set; }
}

bacit-dotnet.MVC/ViewModels/Suggestions/IndexViewModel.cs
namespace bacit_dotnet.MVC.ViewModels.Suggestions
{
    public class IndexViewModel
    {
        public Models.Suggestions[] Suggestions { get; set; }
    }
}

bacit-dotnet.MVC/ViewModels/Suggestions/SuggestionsViewModel.cs
using bacit_dotnet.MVC.Models;

namespace bacit_dotnet.MVC.ViewModels
{
    public class SuggestionsViewModel
    {
        public Suggestions[] Suggestions { get; set; }
    }
}

bacit-dotnet.MVC/Controllers/SuggestionController.cs
using bacit_dotnet.MVC.Interfaces;
using bacit_dotnet.MVC.Models;
using bacit_dotnet.MVC.Repositories;
using bacit_dotnet.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bacit_dotnet.MVC.Controllers
{
    
    // This is the controller class for Suggestions. The controller is the C in MVC
    // The methods in the controller class are used for different CRUD actions related to Suggestions.
    // The class uses dependency injections of the suggestion, team -and userRepository to use different CRUD related Db actions and methods.

    // Keyword Authorize uses Microsoft's authorization system for checking if a user should have access to
    // the page and it's functions. 
    [Authorize]
    public class SuggestionController : Controller
    {
        // Field variables - dependency injections
        private readonly ISuggestionRepository _suggestionRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IUserRepository _userRepository;

        public SuggestionController(ISuggestionRepository suggestionRepository, ITeamRepository teamRepository, IUserRepository userRepository)
        {
            _suggestionRepository = suggestionRepository;
            _teamRepository = teamRepository;
            _userRepository = userRepository;
        }

        // Method returns the index view.
        // The view gets populated with suggestions through the view model.
        public IActionResult Index()
        {
            var indexViewModel = new SuggestionsViewModel()
            {
                Suggestions = _suggestionRepository.GetAllSuggestions()
            };

            return View(indexViewModel);
        }

        //Get
        // Method returns the create view.
        // The view gets populated with teams and users through the view model.
        public IActionResult Create()
        {
            var teams = _teamRepository.GetAllTeamsAndUsers();
            var users = _userRepository.GetUsers();

            var createSuggestionViewModel = new CreateSuggestionViewModel
            {
                Teams = teams,
                Users = users
            };
            
            return View(createSuggestionViewModel);
        }

        //Post
        // Method fires multiple actions for verifying and saving suggestions.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] CreateSuggestionViewModel objSuggestions)
        {
            
            // ModelState checks if the values inputted in the forms are valid.
            // If ModelState is invalid, the method redirects the user back to the create view,
            // and informs the user of an error in the form.
            // This action is another layer of error prevention for a situation where an invalid input
            // would get past the Model [required] restrictions. Stopping an SQLException or Exception 
            
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Verdier er ikke gyldige";
                return RedirectToAction("Create");
            }
            
            // Actions related to img uploading.
            // Using MemoryStream we convert the uploaded img into a byte-stream and copy the stream into a
            // byte-array saved in a local variable.
            
            // The if statement checks if the form inputs contain a file or not and acts accordingly.
            
            var uploadedAttachment = Array.Empty<byte>();
            
            if (objSuggestions.Attachments != null && objSuggestions.Attachments.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objSuggestions.Attachments.CopyTo(memoryStream);
                    uploadedAttachment  = memoryStream.ToArray();
                }
            }
            
            var uploadedAttachmentsAfter = Array.Empty<byte>();
            
            if (objSuggestions.AttchmentsAfter != null && objSuggestions.AttchmentsAfter.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objSuggestions.AttchmentsAfter.CopyTo(memoryStream);
                    uploadedAttachmentsAfter  = memoryStream.ToArray();
                }
            }
            
            // The inputs from the form/view model are added into a new suggestion to be added to the database.

            var newSuggestionId = _suggestionRepository.Add(new Suggestions
            {
                EmployeeId = objSuggestions.EmployeeId,
                Title = objSuggestions.Title,
                Description = objSuggestions.Description,
                Deadline = (DateTime)objSuggestions.Deadline,
                Status = objSuggestions.Status,
                Phase = objSuggestions.Phase,
                Category = objSuggestions.Category,
                TeamId = objSuggestions.TeamId,
                UserId = objSuggestions.UserId,
				
                Attachments = uploadedAttachment,
                AttachmentsAfter = uploadedAttachmentsAfter
            });

            // If statements checks if the value of the new local variable is greater then 0.
            // If the statement is true, the suggestions was successfully added to the database.
            // The local variable newSuggestionId should contain the same int value as the int value in the db.
            
            if (newSuggestionId > 0)
            {
                TempData["success"] = "Forslag ble opprettet";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = "Forslag ble ikke opprettet";
            }

            return RedirectToAction("Create");
        }

        //Get
        // The method return the edit view with populated form field values fetched from the db.
        // The parameter id is used to fetch the correct suggestion from the db.
        public IActionResult Edit(int? id)
        {
            // The if statement checks if the parameter id is empty(null) or 0
            if (id == null || id <= 0)
            {
                return NotFound();
            }

            // _suggestionRepository fetches the correct suggestion from the db, based on the id value.
            var suggestionFromDb = _suggestionRepository.GetSuggestionBySuggestionId(id.Value);

            if (suggestionFromDb == null)
            {
                return NotFound();
            }

            // By using our edit view model, we populate the view with the content gathered from the db.
            // We also populate the view model with users and teams to chose between in different input fields in the form.
            var teams = _teamRepository.GetAllTeamsAndUsers();
            var users = _userRepository.GetUsers();

            var suggestionToEdit = new EditSuggestionViewModel
            {
                SuggestionId = suggestionFromDb.SuggestionId,
                EmployeeId = suggestionFromDb.EmployeeId,
                Title = suggestionFromDb.Title,
                Description = suggestionFromDb.Description,
                Deadline = suggestionFromDb.Deadline,
                Status = suggestionFromDb.Status,
                Phase = suggestionFromDb.Phase,
                Category = suggestionFromDb.Category,
                TeamId = suggestionFromDb.TeamId,
                UserId = suggestionFromDb.UserId,
                Teams = teams,
                Users = users
            };

            return View(suggestionToEdit);
        }

        //Post
        // Method fires multiple actions for verifying and updating suggestions.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromForm]EditSuggestionViewModel objSuggestions)
        {
            
            // ModelState checks if the values inputted in the forms are valid.
            // If ModelState is invalid, the method redirects the user back to the create view,
            // and informs the user of an error in the form.
            // This action is another layer of error prevention for a situation where an invalid input
            // would get past the Model [required] restrictions. Stopping an SQLException or Exception 
            
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Ugyldige verdier i skjema";
                return View(objSuggestions);
            }

            // Actions related to img uploading.
            // Using MemoryStream we convert the uploaded img into a byte-stream and copy the stream into a
            // byte-array saved in a local variable.
            
            // The if statement checks if the form inputs contain a file or not and acts accordingly.
            var uploadedAttachment = Array.Empty<byte>();
            
            if (objSuggestions.Attachment != null && objSuggestions.Attachment.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objSuggestions.Attachment.CopyTo(memoryStream);
                    uploadedAttachment  = memoryStream.ToArray();
                }
            }

            var uploadedAttachmentsAfter = Array.Empty<byte>();
            
            if (objSuggestions.AttchmentsAfter != null && objSuggestions.AttchmentsAfter.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objSuggestions.AttchmentsAfter.CopyTo(memoryStream);
                    uploadedAttachmentsAfter  = memoryStream.ToArray();
                }
            }

            // The inputs from the form/view model are added into a new suggestion to update the row in the db.
            var updatedSuggestion = new Suggestions
            {

bacit-dotnet.MVC/Views/Suggestion/Delete.cshtml
@using Microsoft.VisualBasic
@model bacit_dotnet.MVC.Models.Suggestions

@* ### Delete for Suggestions ### *@

<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4 bg-gr-d">
        <div class="row pb-2">
            <h2 class="text-dark">Slett forslag</h2>
            <hr />
        </div>
        @*
        This line of code will show a summary of all errors at the top of the page.
        <div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="mb-3">
            <label asp-for="SuggestionId">Forslags ID</label>
            <h6>@Model.SuggestionId</h6>
            <input asp-for="SuggestionId" type="hidden" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="EmployeeId">Opprettet av</label>
            <input value="@string.Concat(Model.Employee.FirstName, " ", Model.Employee.LastName)" disabled="" class="form-control" />
        </div>  
        <div class="mb-3">
            <label asp-for="Title">Tittel</label>
            <input asp-for="Title" disabled="disabled" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description">Beskrivelse</label>
            <textarea asp-for="Description" disabled="disabled" class="form-control" style="min-height: 150px"></textarea>
        </div>
        <div class="mb-3">
            <label asp-for="TeamId">Team</label>
            <input asp-for="Team.TeamName" disabled="disabled" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="UserId">Ansvarlig</label>
            <input value="@string.Concat(Model.User.FirstName, " ", Model.User.LastName)" disabled="" class="form-control" />
        </div>           
        <div class="mb-3">
            <label asp-for="Deadline">Tidsfrist</label>
            <input asp-for="Deadline" disabled="disabled" type="date" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Status">Status</label>
            <select asp-for="Status" disabled="disabled" class="form-control">
                <option value="@Model.Status" disabled>@Model.Status</option>
            </select>
        </div>
        <div class="mb-3">
            <label asp-for="Phase">PDSA-fase</label>
            <select asp-for="Phase" disabled="disabled" class="form-control">
                <option value="@Model.Phase" disabled>@Model.Phase</option>
            </select>
        </div>
        <div class="mb-3">
            <label asp-for="Category">Kategori</label>
            <select asp-for="Category" disabled="disabled" class="form-control">
                <option value="@Model.Category" disabled>@Model.Category</option>
            </select>
        </div>
        <br />
        <div class="d-grid pb-3">
            <div class="btn-group" role="group">
                <button type="submit" class="btn btn-light btn-outline-dark btn-lg extra-button-style text-danger" style="width: 150px"><b>Slett</b></button>
                <a asp-controller="Suggestion" asp-action="Index" class="btn btn-light btn-outline-dark btn-lg extra-button-style" style="width: 150px">Tilbake</a>
            </div>
        </div>
    </div>
</form>


<!--This script makes sure that the validation process is done on client-side instead of server-side-->
@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}


    @*<div class="row">
    <div class="d-flex justify-content-center">
        <div class="card col-sm-3 col-md-6">
            <div class="card-header">
                <h5>Lag nytt forslag</h5>
            </div>
            <div class="card-body">

                <div class="mb-3">
                    <label asp-for="EmployeeId" class="form-label">AnsattNummer</label>
                    <input type="text" class="form-control"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Team</label>
                        <input type="text" class="form-control"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Velg Kategori</label>
                        <select class="form-control">
                            <option></option>
                            <option>HMS</option>
                            <option>Kvalitet</option>
                            <option>Ledetid</option>
                            <option>Kostnader</option>
                            <option>Effektivisering</option>
                            <option>Kompetanse</option>
                            <option>Kommunikasjon</option>
                            <option>5S</option>
                            <option>Standardisering</option>
                            <option>Flyt</option>
                            <option>Visualisering</option>
                            <option>Energi</option>
                            <option>Bærekraft</option>
                            <option>Industri 4.0</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Overskrift</label>
                        <input type="text" class="form-control"/>
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Beskrivelse</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="4"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="formFile" class="form-label">Last opp bilde</label>
                        <input class="form-control" type="file" id="formFile">
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-primary">Lagre</button>
                    </div>
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>*@

bacit-dotnet.MVC/Views/Suggestion/Edit.cshtml
@model bacit_dotnet.MVC.ViewModels.EditSuggestionViewModel

@* ### Edit for Suggestions ### *@

<form method="post" enctype="multipart/form-data" asp-action="Edit">
    <div class="border p-3 mt-4 bg-gr-d">
        <div class="row pb-2">
            <h2 class="text-dark">Rediger forslag</h2>
            <hr />
        </div>
        @*
        This line of code will show a summary of all errors at the top of the page.
        <div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="mb-3">
            <label asp-for="SuggestionId">Forslags-ID</label>
            <p>@Model.SuggestionId</p>
            <input asp-for="SuggestionId" type="hidden" class="form-control" />
            <span asp-validation-for="SuggestionId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="EmployeeId">Opprettet av</label>
            <select asp-for="EmployeeId">
                @foreach (var user in Model.Users)
                {
                    if (user.Email.Equals("0"))
                    {
                        continue;
                    }
                    <option value="@user.Id">@user.FirstName @user.LastName</option>
                }
            </select>
            <span asp-validation-for="EmployeeId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Title">Tittel</label>
            <input asp-for="Title" class="form-control" minlength="2" maxlength="30" /><span id="countCharTitle" style="float:right; font-size:14px; color:#4d4d4d;"></span>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description">Beskrivelse</label>
            <textarea asp-for="Description" class="form-control" style="min-height: 150px;"></textarea>
            <span id="countCharDesc" style="float:right; font-size:14px; color:#4d4d4d;"></span>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="mb-3 col-sm-3">
                <label asp-for="TeamId">Team</label>
                <select asp-for="TeamId">
                    @foreach (var team in Model.Teams)
                    {
                        <option value="@team.TeamId">@team.TeamName</option>
                    }
                </select>
                <span asp-validation-for="TeamId" class="text-danger"></span>
            </div>
            <div class="mb-3 col-sm-6">
                <label asp-for="UserId">Ansvarlig</label>
                <select asp-for="UserId">
                    @foreach (var user in Model.Users)
                    {
                        if (user.Email.Equals("0"))
                        {
                            continue;
                        }
                        <option value="@user.Id">@user.FirstName @user.LastName</option>
                    }
                </select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3">
            <label asp-for="Deadline">Tidsfrist</label>
            <input asp-for="Deadline" type="date" class="form-control" />
            <span asp-validation-for="Deadline" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Status">Status</label>
            <select asp-for="Status" class="form-control">
                <option value="@Model.Status" disabled>@Model.Status</option>
                <option value="Opprettet">Opprettet</option>
                <option value="Under behandling">Under behandling</option>
                <option value="Sluttfase">Sluttfase</option>
                <option value="Avslått">Avslått</option>
                <option value="Gjennomført">Gjennomført</option>
            </select>
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Phase">PDSA-fase</label>
            <select asp-for="Phase" class="form-control">
                <option value="@Model.Phase" disabled>@Model.Phase</option>
                <option value="Plan">Plan</option>
                <option value="Do">Do</option>
                <option value="Study">Study</option>
                <option value="Act">Act</option>
            </select>
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Category">Kategori</label>
            <select asp-for="Category" class="form-control">
                <option value="@Model.Category" disabled>@Model.Category</option>
                <option value="HMS">HMS</option>
                <option value="Kvalitet">Kvalitet</option>
                <option value="Ledetid">Ledetid</option>
                <option value="Kostnader">Kostnader</option>
                <option value="Effektivisering">Effektivisering</option>
                <option value="Kompetanse">Kompetanse</option>
                <option value="Kommunikasjon">Kommunikasjon</option>
                <option value="5S">5S</option>
                <option value="Standardisering">Standardisering</option>
                <option value="Flyt">Flyt</option>
                <option value="Visualisering">Visualisering</option>
                <option value="Bærekraft">Bærekraft</option>
                <option value="Industri 4.0">Industri 4.0</option>
            </select>
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>
        <!-- Image -->
        <div class="container-fluid mb-3">
            <div class="row">

                <!-- Image before -->
                <div class="col-sm-6 text-black align-content-center">
                    Bilde før
                    <input asp-for="Attachment" id="imageInputBefore" class="form-control pt-1 mb-1"
                           type="file" accept=".jpg, .png, .jpeg, .heic, .heif" size="1" style="cursor: pointer" value="Choose file" data-max-size="@(8 * 1024.0 * 1024.0)" />

                    <span id="imageSizeWarningBefore" class="text-danger" style="display: none;"></span>
                    <span id="imageTypeWarningBefore" class="text-danger" style="display: none"></span>
                </div>

                <!-- Image after -->
                <div class="col-sm-6 text-black align-content-center">
                        Bilde etter
                            <input asp-for="AttchmentsAfter" id="imageInputAfter" class="form-control pt-1"
                                   type="file" accept=".jpg, .png, .jpeg, .heic, .heif" size="1" style="cursor: pointer" value="Choose file" data-max-size="@(8 * 1024.0 * 1024.0)" />
        
                            <span id="imageSizeWarningAfter" class="text-danger" style="display: none;"></span>
                            <span id="imageTypeWarningAfter" class="text-danger" style="display: none"></span>
                        </div>
                <!-- Image preview field -->

                @*<img id="imagePreview" style="max-height: 300px; max-width: 300px; display: none;" />*@

            </div>
        </div>
        <br />
        <div class="d-grid pb-3">
            <div class="btn-group" role="group">
                <button id="submitBtn" type="submit" class="btn btn-dark btn-outline-dark text-white btn-lg extra-button-style-b" style="width: 150px">Oppdater</button>
                <a asp-controller="Suggestion" asp-action="Index" class="btn btn-light btn-outline-dark btn-lg extra-button-style" style="width: 150px">Tilbake</a>
            </div>
        </div>
    </div>
</form>


<!--This script makes sure that the validation process is done on client-side instead of server-side-->
@section Scripts{

    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/createSuggestion.js"></script>

}

    @*
    This script is used to count the remaining characters in the create suggestion form for the "title" and "description" fields.
    The function will count backwards from the fields' maximum value until it reaches zero.
*@
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById('Title').onkeyup = function () {
                document.getElementById('countCharTitle').innerHTML = (30 - this.value.length) + "/30";
            };
        });

        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById('Description').onkeyup = function () {
                document.getElementById('countCharDesc').innerHTML = (500 - this.value.length) + "/500";
            };
        });
    </script>