bacit-dotnet.MVC/Controllers/TeamController.cs
using bacit_dotnet.MVC.Interfaces;
using bacit_dotnet.MVC.Models;
using bacit_dotnet.MVC.Repositories;
using bacit_dotnet.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace bacit_dotnet.MVC.Controllers
{
    // This is the controller class for Teams. The controller is the C in MVC
    // The methods in the controller class are used for different CRUD actions related to Teams.
    // The class uses dependency injections of the team -and userRepository to use different CRUD related Db actions and methods.
    
    // Keyword Authorize uses Microsoft's authorization system for checking if a user should have access to
    // the page and it's functions.
	[Authorize(Roles = "Administrator")]
    public class TeamController : Controller
    {
        // Field variables - dependency injections
        private readonly ITeamRepository _teamRepository;
        private readonly IUserRepository _userRepository;
        
        public TeamController(ITeamRepository teamRepository, IUserRepository userRepository)
        {
            _teamRepository = teamRepository;
            _userRepository = userRepository;
        }

        // Method returns the index view.
        // The view gets populated with teams through the view model.
        [HttpGet]
        public IActionResult Index()
        {
            var indexViewModel = new TeamViewModel()
            {
                Teams = _teamRepository.GetAllTeamsAndUsers()
            };

            return View(indexViewModel);
        }

        // Method returns the create view.
        // The view gets populated with users through the view model.
        [HttpGet]
        public IActionResult Create()
        {
            var users = _userRepository.GetUsers();

            var createTeamViewModel = new CreateTeamViewModel
            {
                Users = users
            };

            return View(createTeamViewModel);
        }

        //Post
        // Method fires multiple actions for verifying and saving teams.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateTeamViewModel objTeams)
        {
            // ModelState checks if the values inputted in the forms are valid.
            // If ModelState is invalid, the method redirects the user back to the create view,
            // and informs the user of an error in the form.
            // This action is another layer of error prevention for a situation where an invalid input
            // would get past the Model [required] restrictions. Stopping an SQLException or Exception
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Ugyldige verdier i skjema";
                return RedirectToAction("Create");
            }

            // The inputs from the form/view model are added into a new team to be added to the database.
            var newTeamId = _teamRepository.Add(new Teams
            {
                UserId = objTeams.UserId,
                TeamName = objTeams.TeamName,
            });

            // If statements checks if the value of the new local variable is greater then 0.
            // The local variable newTeamId should contain the same int value as the int value in the db.
            // If the statement is true, the team was successfully added to the database.
            if (newTeamId > 0)
            {
                TempData["success"] = "Team har blitt opprettet!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Team ikke opprettet!";
            }

            return RedirectToAction("Create");
        }

        //Get
        // The method return the edit view with populated form field values fetched from the db.
        // The parameter id is used to fetch the correct team from the db.
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            // The if statement checks if the parameter id is empty(null) or 0
            if (id == null || id <= 0)
            {
                return NotFound();
            }

            // _userRepository fetches the correct team from the db, based on the id value.
            var teamFromDb = _teamRepository.GetTeamAndUserByTeamId(id.Value);

            if (teamFromDb == null)
            {
                return NotFound();
            }
            
            // By using our edit view model, we populate the view with the content gathered from the db.
            // We also populate the view model with users to chose between in an input field in the form.
            var users = _userRepository.GetUsers();

            var teamAndUserGatheredFromDb = new EditTeamViewModel()
            {
                TeamId = teamFromDb.TeamId,
                TeamName = teamFromDb.TeamName,
                UserId = teamFromDb.UserId,
                Users = users
            };

            return View(teamAndUserGatheredFromDb);
        }

        //Post
        // Method fires multiple actions for verifying and updating teams.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditTeamViewModel objTeams)
        {
            // ModelState checks if the values inputted in the forms are valid.
            // If ModelState is invalid, the method redirects the user back to the create view,
            // and informs the user of an error in the form.
            // This action is another layer of error prevention for a situation where an invalid input
            // would get past the Model [required] restrictions. Stopping an SQLException or Exception 
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Ugyldige verdier i skjema";
                return RedirectToAction("Edit", objTeams.TeamId);
            }
            
            // The inputs from the form/view model are added into a new team to update the row in the db.
            var updatedTeam = new Teams
            {
                TeamId = objTeams.TeamId,
                TeamName = objTeams.TeamName,
                UserId = objTeams.UserId,
            };

            // If statements checks if the value of the new local variable is greater then 0.
            // The local variable newTeamId should contain the same int value as the int value in the db.
            // If the statement is true, the suggestions was successfully updated in the database.
            var rowsAffectedByUpdate = _teamRepository.Update(updatedTeam);
            if (rowsAffectedByUpdate > 0)
            {
                TempData["success"] = "Team har blitt oppdatert";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Team ble ikke oppdatert";
            }
            return RedirectToAction("Edit", objTeams.TeamId);
        }

        //Get
        // The method return the delete view with populated form field values fetched from the db,
        // to display what will be deleted.
        // The parameter id is used to fetch the correct suggestion from the db.
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            // The if statement checks if the parameter id is empty(null) or 0
            if (id == null || id <= 0)
            {
                return NotFound();
            }
            
            // The if statements checks if the team to be deleted is connected(foreign key) to a suggestions
            // or Justdoit in the db. If the user is trying to delete a connected team, the if statements
            // handles the actions and avoids the potential following SQLException.
            if (_teamRepository.IsTeamInUseSuggestion(id.Value))
            {
                TempData["error"] = "Kan ikke slette team. Team tilhører et forslag!";
                return RedirectToAction("Index");
            }
            
            if (_teamRepository.IsTeamInUseJustdoit(id.Value))
            {
                TempData["error"] = "Kan ikke slette team. Team tilhører et JustDoIt!";
                return RedirectToAction("Index");
            }

            // By using the team model, we populate the view with the content gathered from the db.
            var teamFromDb = _teamRepository.GetTeamAndUserByTeamId(id.Value);

            if (teamFromDb == null)
            {
                return NotFound();
            }

            return View(teamFromDb);
        }

        //Delete
        // Method fires multiple actions for verifying and deleting teams.
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteTeam(int? id)
        {
            // The if statement checks if the parameter id is empty(null) or 0
            if (id == null || id <= 0)
            {
                return NotFound();
            }

            // If statements checks if the bool value of the new local variable is true or false.
            // If the statement is true, the team was successfully deleted in the database.
            var hasRowBeenDeleted = _teamRepository.Delete(id.Value);

            if (!hasRowBeenDeleted)
            {
                TempData["error"] = "Team ble ikke slettet";
                return NotFound();
            }

            TempData["success"] = "Team har blitt slettet";

            return RedirectToAction("Index");
        }
    }
}

bacit-dotnet.MVC/Controllers/UsersController.cs
using bacit_dotnet.MVC.Interfaces;
using bacit_dotnet.MVC.Models;
using bacit_dotnet.MVC.Models.Account;
using bacit_dotnet.MVC.Repositories;
using bacit_dotnet.MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Manage.Internal;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace bacit_dotnet.MVC.Controllers
{
    // This is the controller class for Users. The controller is the C in MVC
    // The methods in the controller class are used for different CRUD actions related to Users.
    // The class uses dependency injections of the userRepository to use different CRUD related Db actions and methods.
    
    // Keyword Authorize uses Microsoft's authorization system for checking if a user should have access to
    // the page and it's functions. 
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        // Field variables - dependency injections
        private readonly IUserRepository userRepository;

        public UsersController(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }
        
        // Method returns the index view.
        // The view gets populated with users through the view model.
        [HttpGet]
        public IActionResult Index()
        {
            var model = new UserViewModel();
            model.Users = userRepository.GetUsers();

            return View(model);
        }

        [HttpPost]
        public IActionResult Save(UserViewModel model)
        {

            UserEntity newUser = new UserEntity
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                EmployeeNumber = model.EmployeeNumber,
                Role = model.Role,
                Team = model.Team,
            };
            var roles = new List<string>();
            if (model.IsAdmin)
                roles.Add("Administrator");
            userRepository.Update(newUser, roles);

            return RedirectToAction("Index");
        }

        //[HttpPost]
        //public IActionResult Delete(string email)
        //{
        //    userRepository.Delete(email);
        //    return RedirectToAction("Index");
        //}

     
        public IActionResult Cancel()
        {
            return RedirectToAction("Index");

        }

        public IActionResult Edit(string? email)
        {
            var model = new UserViewModel();
            model.Users = userRepository.GetUsers();
            if (email != null)
            {
                var currentUser = model.Users.FirstOrDefault(x => x.Email == email);
                if (currentUser != null)
                {
                    model.EmployeeNumber = currentUser.EmployeeNumber;
                    model.Email = currentUser.Email;
                    model.FirstName = currentUser.FirstName;
                    model.LastName = currentUser.LastName;
                    model.Role = currentUser.Role;
                    model.Team = currentUser.Team;
                    model.IsAdmin = userRepository.IsAdmin(currentUser.Email);
                }
            }
            return View(model);
        }
    }
}

bacit-dotnet.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bacit_dotnet.MVC</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-nav border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Image/nordic_door_logo.png" width="150px" height="auto" alt="nordicdoorlogo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Hjem</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Suggestion" asp-action="Index">Forslag</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Justdoit" asp-action="Index">Justdoit</a>
                            </li>
                        @*Sjekker om bruker er rollen admin, og gir tilgang til teams og brukere om bruker er admin*@
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Users" asp-action="Index">Brukere</a>
                            </li>
                            }
                        </ul>
	                <ul class="navbar-nav flex-grow-2" style="float: right;">
		                <li class="nav-item">
			                <a class="nav-link text-light">Ansattnummer: @User.Identity.Name</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="LogOff">Logg ut</a>
		                </li>
	                </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container-lg">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    @*<footer class="footer text-muted position-absolute bottom-0 p-3 m-3">
    <div class="container">
    &copy; 2022 - nordicdoor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="//code.iconify.design/1/1.0.6/iconify.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

bacit-dotnet.MVC/Views/Shared/_LayoutButton.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bacit_dotnet.MVC</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-nav border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Image/nordic_door_logo.png" width="150px" height="auto" alt="nordicdoorlogo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Hjem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Suggestion" asp-action="Index">Forslag</a>
                        </li>
	                    <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Justdoit" asp-action="Index">Justdoit</a>
	                    </li>
                        @*Sjekker om bruker er rollen admin, og gir tilgang til teams og brukere om bruker er admin*@
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Users" asp-action="Index">Brukere</a>
                            </li>
                            }
                        </ul>
	                <ul class="navbar-nav flex-grow-2" style="float: right;">
		                <li class="nav-item">
			                <a class="nav-link text-light">Ansattnummer: @User.Identity.Name</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="LogOff">Logg ut</a>
		                </li>
	                </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-lg p-0">



        @*

        The following code will create a popup modal for all index-pages.
        In this popup the user may choose what type of suggestion they want to create.

        *@

        <div class="text-center">

            <!-- Button trigger modal -->

            <a type="button" class="btn btn-outline-dark btn-lg create-suggestion-main p-4 mb-3" style="width:300px;" data-bs-toggle="modal" data-bs-target="#createSuggestion">
                Opprett forslag
            </a>

            @*

        The following code adds a popup modal which allows the user to select what type of suggestion they want to create.
        The popup can be closed by pressing the x-button toggle in the upper right corner or click anywhere outside of the popup. On a desktop computer a user can also press the ESC key.

            *@
            <div class="modal fade" id="createSuggestion" tabindex="-1" aria-labelledby="createSuggestionLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="createSuggestionLabel">Opprett forslag</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="d-grid">
                                <div class="btn-group-vertical" role="group">
                                    <a asp-area="" asp-controller="Suggestion" asp-action="Create" class="btn btn-light btn-outline-dark btn-lg p-4 mb-3 extra-button-style">
                                        <span class="iconify extra-iconify-mdi" data-icon="mdi-file-document-outline"></span>
                                        <h4 class="d-inline">Ordinære forslag</h4>
                                    </a>
                                    <a asp-area="" asp-controller="Justdoit" asp-action="Create" class="btn btn-light btn-outline-dark btn-lg p-4 extra-button-style">
                                        <span class="iconify extra-iconify-mdi" data-icon="mdi-run-fast"></span>
                                        <h4 class="d-inline">Just do it</h4>
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr />



        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    @*<footer class="footer text-muted position-absolute bottom-0 p-3 m-3">
    <div class="container">
    &copy; 2022 - nordicdoor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="//code.iconify.design/1/1.0.6/iconify.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

bacit-dotnet.MVC/Views/Shared/_Notification.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" 
    integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer">
</script>

@if (TempData.ContainsKey("success"))
{
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["success"]('@TempData["success"]')
    </script>
}

@if (TempData.ContainsKey("error"))
{
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["error"]('@TempData["error"]')
    </script>
}