bacit-dotnet.MVC/Models/Justdoit/Justdoit.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection.Metadata;

namespace bacit_dotnet.MVC.Models
{
    // This is the model for JustDoIt. The Model is the M in MVC
    // The model is like a reflection of the related Db table, in this case the justdoit Db table.
    // Each variable in the model reflects each column in the Db table.
    
    // Using [DataAnnotations] we can set up client-side validation for each variable/column before sending sending the data to the Db.
    // Even though many of the [DataAnnotations] keywords are useful when using db migrations, we have mainly done all db edits manually.
    
    // [Table] defines the table name in the Db the model is reflecting.
    // [Key] defines the primary key of the table.
    // [Required] defines that the variable can not be null. By adding (ErrorMessage="") we can also define a custom error message.
    // [Range] defines that the int value must be a value between 1 and ints max possible value.
    // [StringLenght] defines that the string lenght has a maximum and minimum lenght. 
    // [Foreign Key] defines that the variable is a foreign key connected to another table.

    [Table("justdoit")]
    public class Justdoit
    {
        [Key]
        public int JustdoitId { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en ansatt.")]
        [Range(1, int.MaxValue)]
        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "Vennligst fyll inn tittelen.")]
        [StringLength(30,MinimumLength = 2)]
        public string? Title { get; set; }

        [Required(ErrorMessage = "Vennligst fyll inn beskrivelsen.")]
        [StringLength(500, MinimumLength = 2)]
        public string? Description { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;
        
        [Required(ErrorMessage = "Vennligst velg en kategori.")]
        public string? Category { get; set; }

        public byte[]? Attachments { get; set; }

        public byte[]? AttachmentAfter { get; set; }
        
        [ForeignKey("teamId")]
        [Required(ErrorMessage = "Vennligst velg et gyldig team.")]
        [Range(1, int.MaxValue)]
        public int TeamId { get; set; }
        
        // a variable that holds a team obj
        public Teams? Team { get; set; }

        // a variable that holds a user obj
        public UserEntity? Employee { get; set; }
    }
}

bacit-dotnet.MVC/ViewModels/Justdoit/CreateJustdoitViewModel.cs
using System.ComponentModel.DataAnnotations;
using bacit_dotnet.MVC.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace bacit_dotnet.MVC.ViewModels
{
    public class CreateJustdoitViewModel
    {
        public IFormFile? Attachments { get; set; }

        public IFormFile? AttachmentsAfter { get; set; }
        
        [ValidateNever]
        public Teams[] Teams { get; set; }
        
        [ValidateNever]
        public UserEntity[] Users { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en ansatt.")]
        [Range(1, int.MaxValue)]
        public int? EmployeeId { get; set; }

        [Required(ErrorMessage = "Vennligst fyll inn tittelen.")]
        [StringLength(30,MinimumLength = 2)]
        public string? Title { get; set; }

        [Required(ErrorMessage = "Vennligst fyll inn beskrivelsen.")]
        [StringLength(500, MinimumLength = 2)]
        public string? Description { get; set; }
        
        [Required(ErrorMessage = "Vennligst velg en kategori.")]
        public string? Category { get; set; }

        [Required(ErrorMessage = "Vennligst velg et gyldig team.")]
        [Range(1, int.MaxValue)]
        public int TeamId { get; set; }
    }
}

bacit-dotnet.MVC/ViewModels/Justdoit/EditJustdoitViewModel.cs
using System.ComponentModel.DataAnnotations;
using bacit_dotnet.MVC.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace bacit_dotnet.MVC.ViewModels.Justdoit;

public class EditJustdoitViewModel
{
    [ValidateNever]
    public Teams[] Teams { get; set; }
   
    [ValidateNever] 
    public UserEntity[] Users { get; set; }
    public int TeamId { get; set; }
    
    public int JustdoitId { get; set; }

    [Range(1, int.MaxValue)]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(30,MinimumLength = 2)]
    public string? Title { get; set; }

    [Required]
    [StringLength(500, MinimumLength = 2)]
    public string? Description { get; set; }
    
    [Required]
    public string? Category { get; set; }
    
    public IFormFile? Attachment { get; set; }
    
    public IFormFile? AttachmentsAfter { get; set; }

}

bacit-dotnet.MVC/ViewModels/Justdoit/JustdoitViewModel.cs
using bacit_dotnet.MVC.Models;

namespace bacit_dotnet.MVC.ViewModels
{
    public class JustdoitViewModel
    {
        public Models.Justdoit[] Justdoit { get; set; }
    }
}

bacit-dotnet.MVC/Controllers/JustdoitController.cs
using bacit_dotnet.MVC.Interfaces;
using bacit_dotnet.MVC.Models;
using bacit_dotnet.MVC.Repositories;
using bacit_dotnet.MVC.ViewModels;
using bacit_dotnet.MVC.ViewModels.Justdoit;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bacit_dotnet.MVC.Controllers
{
    
    // This is the controller class for JustDoIt. The controller is the C in MVC
    // The methods in the controller class are used for different CRUD actions related to JustDoIt.
    // The class uses dependency injections of the justdoit, team -and userRepository to use different CRUD related Db actions and methods.
    
    // Keyword Authorize uses Microsoft's authorization system for checking if a user should have access to
    // the page and it's functions. 
    [Authorize]
    public class JustdoitController : Controller
    {
        // Field variables - dependency injections
        private readonly IJustdoitRepository _justdoitRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly IUserRepository _userRepository;

        public JustdoitController(IJustdoitRepository useRepository, ITeamRepository teamRepository, IUserRepository userRepository)
        {
            _justdoitRepository = useRepository;
            _teamRepository = teamRepository;
            _userRepository = userRepository;
        }

        // Method returns the index view.
        // The view gets populated with justdoit suggestions through the view model.
        public IActionResult Index()
        {
            var indexViewModel = new JustdoitViewModel()
            {
                Justdoit = _justdoitRepository.GetAllJustdoit()
            };

            return View(indexViewModel);
        }

        // Get
        // Method returns the create view.
        // The view gets populated with teams and users through the view model.
        public IActionResult Create()
        {
            var teams = _teamRepository.GetAllTeamsAndUsers();
            var users = _userRepository.GetUsers()
                ;
            var createSuggestionViewModel = new CreateJustdoitViewModel()
            {
                Teams = teams,
                Users = users
            };
            
            return View(createSuggestionViewModel);
        }

        // Post
        // Method fires multiple actions for verifying and saving JustDoIt suggestions.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm]CreateJustdoitViewModel objJustdoit)
        {
            // ModelState checks if the values inputted in the forms are valid.
            // If ModelState is invalid, the method redirects the user back to the create view,
            // and informs the user of an error in the form.
            // This action is another layer of error prevention for a situation where an invalid input
            // would get past the Model [required] restrictions. Stopping an SQLException or Exception 
            
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Verdier er ikke gyldige";
                return RedirectToAction("Create");
            }

            
            // Actions related to img uploading.
            // Using MemoryStream we convert the uploaded img into a byte-stream and copy the stream into a
            // byte-array saved in a local variable.
            
            // The if statement checks if the form inputs contain a file or not and acts accordingly.

            var uploadedAttachment = Array.Empty<byte>();
            
            if(objJustdoit.Attachments != null && objJustdoit.Attachments.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objJustdoit.Attachments.CopyTo(memoryStream);
                    uploadedAttachment = memoryStream.ToArray();
                }
            }
            
            var uploadedAttachmentsAfter = Array.Empty<byte>();
            
            if (objJustdoit.AttachmentsAfter != null && objJustdoit.AttachmentsAfter.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objJustdoit.AttachmentsAfter.CopyTo(memoryStream);
                    uploadedAttachmentsAfter  = memoryStream.ToArray();
                }
            }

            // The inputs from the form/view model are added into a new JustDoIt to be added to the database.
            
            var newJustdoitId = _justdoitRepository.Add(new Justdoit
            {
                EmployeeId = objJustdoit.EmployeeId.Value,
                Title = objJustdoit.Title,
                Description = objJustdoit.Description,
                Category = objJustdoit.Category,
                TeamId = objJustdoit.TeamId,
				
                Attachments = uploadedAttachment,
                AttachmentAfter = uploadedAttachmentsAfter
            });

            
            // If statements checks if the value of the new local variable is greater then 0.
            // If the statement is true, the justdoit suggestions was successfully added to the database.
            // The local variable newJustdoitId should contain the same int value as the int value in the db.
            
            if (newJustdoitId > 0)
            {
                TempData["success"] = "JustDoIt ble opprettet";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = "JustDoIt ble ikke opprettet";
            }

            return RedirectToAction("Create");
        }

        // Get
        // The method return the edit view with populated form field values fetched from the db.
        // The parameter id is used to fetch the correct Justdoit suggestion from the db.
        public IActionResult Edit(int? id)
        {
            // The if statement checks if the parameter id is empty(null) or 0
            if (id == null || id <= 0)
            {
                return NotFound();
            }

            // _justdoitRepository fetches the correct justdoit suggestion from the db, based on the id value.
            var justdoitFromDb = _justdoitRepository.GetJustdoitByJustdoitId(id.Value);

            if (justdoitFromDb == null)
            {
                return NotFound();
            }

            // By using our edit view model, we populate the view with the content gathered from the db.
            // We also populate the view model with users and teams to chose between in different input fields in the form.
            var teams = _teamRepository.GetAllTeamsAndUsers();
            var users = _userRepository.GetUsers();

            var justdoitToEdit = new EditJustdoitViewModel()
            {
                JustdoitId = justdoitFromDb.JustdoitId,
                EmployeeId = justdoitFromDb.EmployeeId,
                Title = justdoitFromDb.Title,
                Description = justdoitFromDb.Description,
                Category = justdoitFromDb.Category,
                TeamId = justdoitFromDb.TeamId,
                Teams = teams,
                Users = users
            };
            
            return View(justdoitToEdit);
        }

        //Post
        // Method fires multiple actions for verifying and updating JustDoIt suggestions.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromForm]EditJustdoitViewModel objJustdoit)
        {
            // ModelState checks if the values inputted in the forms are valid.
            // If ModelState is invalid, the method redirects the user back to the create view,
            // and informs the user of an error in the form.
            // This action is another layer of error prevention for a situation where an invalid input
            // would get past the Model [required] restrictions. Stopping an SQLException or Exception 
            
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Ugyldige verdier i skjem";
                return View(objJustdoit);
            }
            
            // Actions related to img uploading.
            // Using MemoryStream we convert the uploaded img into a byte-stream and copy the stream into a
            // byte-array saved in a local variable.
            
            // The if statement checks if the form inputs contain a file or not and acts accordingly.
            var uploadedAttachment = Array.Empty<byte>();
            
            if (objJustdoit.Attachment != null && objJustdoit.Attachment.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objJustdoit.Attachment.CopyTo(memoryStream);
                    uploadedAttachment  = memoryStream.ToArray();
                }
            }
            
            var uploadedAttachmentsAfter = Array.Empty<byte>();
            
            if (objJustdoit.AttachmentsAfter != null && objJustdoit.AttachmentsAfter.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    objJustdoit.AttachmentsAfter.CopyTo(memoryStream);
                    uploadedAttachmentsAfter  = memoryStream.ToArray();
                }
            }
            
            // The inputs from the form/view model are added into a new JustDoIt to update the row in the db.
            var updatedJustdoit = new Justdoit()
            {
                JustdoitId = objJustdoit.JustdoitId,
                EmployeeId = objJustdoit.EmployeeId,
                Title = objJustdoit.Title,
                Description = objJustdoit.Description,
                Category = objJustdoit.Category,
                TeamId = objJustdoit.TeamId,
                
                Attachments = uploadedAttachment,
                AttachmentAfter = uploadedAttachmentsAfter

bacit-dotnet.MVC/Views/Justdoit/Create.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers


@* ### Create for Just do it ### *@

@model bacit_dotnet.MVC.ViewModels.CreateJustdoitViewModel

<form method="post" enctype="multipart/form-data">
    <div class="border p-3 mt-4 bg-gr-d">
        <div class="row pb-2">
            <h3 class="text-dark">Legg til ny Just Do It</h3>
            <hr />
        </div>
        @*
            This line of code will show a summary of all errors at the top of the page.
            <div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="mb-3">
            <label asp-for="EmployeeId">Opprettet av</label>
            <select asp-for="EmployeeId">
                @foreach (var user in Model.Users)
                {
                    if (@User.Identity.Name == @user.Email)
                    {
                        <option value="@user.Id" selected>@user.FirstName @user.LastName</option>
                    }
                    if (user.Email.Equals("0") || user.Email.Equals(@User.Identity.Name))
                    {
                        continue;
                    }
                    <option value="@user.Id">@user.FirstName @user.LastName</option>
                }
            </select>
            <span asp-validation-for="EmployeeId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Title">Tittel</label>
            <input asp-for="Title" class="form-control" minlength="2" maxlength="30" /><span id="countCharTitle" class="count-max-length">30/30</span>
            <span asp-validation-for="Title" class="text-danger">
            </span>
        </div>
        <div class="mb-3">
            <label asp-for="Description">Beskrivelse</label>
            <textarea asp-for="Description" class="form-control" style="min-height: 150px;"></textarea>
            <span id="countCharDesc" style="float:right; font-size:14px; color:#4d4d4d;">500/500</span>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TeamId">Team</label>
            <select asp-for="TeamId">
                <option value="" selected disabled>Velg et Team</option>
                @foreach (var team in Model.Teams)
                {
                    <option value="@team.TeamId">@team.TeamName</option>
                }
            </select>
            <span asp-validation-for="TeamId" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Category">Kategori</label>
            <select asp-for="Category" class="form-control">
                <option value="" selected disabled>Velg en kategori</option>
                <option value="HMS">HMS</option>
                <option value="Kvalitet">Kvalitet</option>
                <option value="Ledetid">Ledetid</option>
                <option value="Kostnader">Kostnader</option>
                <option value="Effektivisering">Effektivisering</option>
                <option value="Kompetanse">Kompetanse</option>
                <option value="Kommunikasjon">Kommunikasjon</option>
                <option value="5S">5S</option>
                <option value="Standardisering">Standardisering</option>
                <option value="Flyt">Flyt</option>
                <option value="Visualisering">Visualisering</option>
                <option value="Bærekraft">Bærekraft</option>
                <option value="Industri 4.0">Industri 4.0</option>
            </select>
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>

        <!-- Image -->
        <div class="container-fluid mb-3">
            <div class="row">

                <!-- Image before -->
                <div class="col-sm-6 text-black align-content-center">
                    Bilde før
                    <input asp-for="Attachments" id="imageInputBefore" class="form-control pt-1 mb-1"
                           type="file" accept=".jpg, .png, .jpeg, .heic, .heif" size="1" style="cursor: pointer" value="Choose file" data-max-size="@(8 * 1024.0 * 1024.0)" />

                    <span id="imageSizeWarningBefore" class="text-danger" style="display: none;"></span>
                    <span id="imageTypeWarningBefore" class="text-danger" style="display: none"></span>
                </div>

                <!-- Image after -->
                <div class="col-sm-6 text-black align-content-center">
                    Bilde etter
                    <input asp-for="AttachmentsAfter" id="imageInputAfter" class="form-control pt-1"
                           type="file" accept=".jpg, .png, .jpeg, .heic, .heif" size="1" style="cursor: pointer" value="Choose file" data-max-size="@(8 * 1024.0 * 1024.0)" />

                    <span id="imageSizeWarningAfter" class="text-danger" style="display: none;"></span>
                    <span id="imageTypeWarningAfter" class="text-danger" style="display: none"></span>
                </div>
                <!-- Image preview field -->
                @*<img id="imagePreview" style="max-height: 300px; max-width: 300px; display: none;"/>*@

            </div>

            <br />

            @*
                Creates a group of buttons for submit and return to list buttons.
                The buttons are set to 100% width of the parent class.
                Also using a custom button class that extends the bootstrap button classes to specify the font-size.
            *@
            <div class="d-grid pb-3">
                <div class="btn-group" role="group">
                    <button id="submitBtn" type="submit" class="btn btn-dark btn-lg btn-outline-dark text-white extra-button-style-b">Opprett</button>
                    <a asp-controller="Home" asp-action="Index" class="btn btn-light btn-outline-dark btn-lg extra-button-style">Tilbake</a>
                </div>
            </div>
        </div>
    </div>
    </div>
</form>

<!--This script makes sure that the validation process is done on client-side instead of server-side-->

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
    <script src="~/js/createSuggestion.js"></script>
}

@*
    This script is used to count the remaining characters in the create suggestion form for the "title" and "description" fields.
    The function will count backwards from the fields' maximum value until it reaches zero.
*@
<script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById('Title').onkeyup = function () {
                document.getElementById('countCharTitle').innerHTML = (30 - this.value.length) + "/30";
            };
        });

        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById('Description').onkeyup = function () {
                document.getElementById('countCharDesc').innerHTML = (500 - this.value.length) + "/500";
            };
        });</script>

bacit-dotnet.MVC/Views/Justdoit/Delete.cshtml
@model Justdoit

@* ### Delete for Just do it ### *@

<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4 bg-gr-d">
        <div class="row pb-2">
            <h2 class="text-dark">Slette Just-do-it-forslag</h2>
            <hr />
        </div>
        @*
        This line of code will show a summary of all errors at the top of the page.
        <div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="mb-3">
            <label asp-for="JustdoitId">Forslags ID</label>
            <h6>@Model.JustdoitId</h6>
            <input asp-for="JustdoitId" type="hidden" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="EmployeeId">Opprettet av</label>
            <input value="@string.Concat(Model.Employee.FirstName, " ", Model.Employee.LastName)" disabled="" class="form-control" />
        </div>  
        <div class="mb-3">
            <label asp-for="Title">Tittel</label>
            <input asp-for="Title" disabled="disabled" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description">Beskrivelse</label>
            <textarea asp-for="Description" disabled="disabled" class="form-control" style="min-height: 150px;"></textarea>
        </div>
        <div class="mb-3">
            <label asp-for="TeamId">Team</label>
            <input asp-for="Team.TeamName" disabled="disabled" class="form-control" />
        </div>          
        <div class="mb-3">
            <label asp-for="Category">Kategori</label>
            <select asp-for="Category" disabled="disabled" class="form-control">
                <option value="@Model.Category" disabled>@Model.Category</option>
            </select>
        </div>
        
        <br />
        <div class="d-grid pb-3">
            <div class="btn-group" role="group">
                <button type="submit" class="btn btn-light btn-outline-dark btn-lg extra-button-style text-danger" style="width: 150px"><b>Slett</b></button>
                <a asp-controller="Justdoit" asp-action="Index" class="btn btn-light btn-outline-dark btn-lg extra-button-style" style="width: 150px">Tilbake</a>
            </div>
        </div>
    </div>
</form>


<!--This script makes sure that the validation process is done on client-side instead of server-side-->
@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}

bacit-dotnet.MVC/Views/Justdoit/Edit.cshtml
@model bacit_dotnet.MVC.ViewModels.Justdoit.EditJustdoitViewModel

@* ### Edit for Just do it ### *@

<form method="post" enctype="multipart/form-data" asp-action="Edit">
    <div class="border p-3 mt-4 bg-gr-d">
        <div class="row pb-2">
            <h2 class="text-dark">Rediger Just-Do-It-forslag</h2>
            <hr/>
        </div>
        @*
        This line of code will show a summary of all errors at the top of the page.
        <div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="mb-3">
            <label asp-for="JustdoitId">Forslags ID</label>
            <h6>@Model.JustdoitId</h6>
            <input asp-for="JustdoitId" type="hidden" class="form-control"/>
            <span asp-validation-for="JustdoitId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="EmployeeId">Opprettet av</label>
            <select asp-for="EmployeeId">
                @foreach (var user in Model.Users)
                {
                    if (user.Email.Equals("0"))
                    {
                        continue;
                    }
                    <option value="@user.Id">@user.FirstName @user.LastName</option>
                }
            </select>
            <span asp-validation-for="EmployeeId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Title">Tittel</label>
            <input asp-for="Title" class="form-control" minlength="2" maxlength="30" /><span id="countCharTitle" style="float:right; font-size:14px; color:#4d4d4d;"></span>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description">Beskrivelse</label>
            <textarea asp-for="Description" class="form-control" style="min-height: 150px;"></textarea>
            <span id="countCharDesc" style="float:right; font-size:14px; color:#4d4d4d;"></span>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TeamId">Team</label>
            <select asp-for="TeamId">
                @foreach (var team in Model.Teams)
                {
                    <option value="@team.TeamId">@team.TeamName</option>
                }
            </select>
            <span asp-validation-for="TeamId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Category">Kategori</label>
            <select asp-for="Category" class="form-control">
                <option value="@Model.Category" disabled>@Model.Category</option>
                <option value="HMS">HMS</option>
                <option value="Kvalitet">Kvalitet</option>
                <option value="Ledetid">Ledetid</option>
                <option value="Kostnader">Kostnader</option>
                <option value="Effektivisering">Effektivisering</option>
                <option value="Kompetanse">Kompetanse</option>
                <option value="Kommunikasjon">Kommunikasjon</option>
                <option value="5S">5S</option>
                <option value="Standardisering">Standardisering</option>
                <option value="Flyt">Flyt</option>
                <option value="Visualisering">Visualisering</option>
                <option value="Bærekraft">Bærekraft</option>
                <option value="Industri 4.0">Industri 4.0</option>
            </select>
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>
        <div class="container-fluid mb-3">
            <div class="row">

                <!-- Image before -->
                <div class="col-sm-5 text-black align-content-center">
                    Last opp et bilde
                    <input asp-for="Attachment" id="imageInputBefore" class="form-control pt-1 mb-1"
                           type="file" accept=".jpg, .png, .jpeg, .heic, .heif" size="1" style="cursor: pointer" value="Choose file" data-max-size="@(8 * 1024.0 * 1024.0)"/>

                    <span id="imageSizeWarningBefore" class="text-danger" style="display: none;"></span>
                    <span id="imageTypeWarningBefore" class="text-danger" style="display: none"></span>
                </div>
                
                <!-- Image after -->
                <div class="col-sm-5 text-black align-content-center">
                        Bilde etter
                            <input asp-for="AttachmentsAfter" id="imageInputAfter" class="form-control pt-1"
                                   type="file" accept=".jpg, .png, .jpeg, .heic, .heif" size="1" style="cursor: pointer" value="Choose file" data-max-size="@(8 * 1024.0 * 1024.0)" />
        
                            <span id="imageSizeWarningAfter" class="text-danger" style="display: none;"></span>
                            <span id="imageTypeWarningAfter" class="text-danger" style="display: none"></span>
                        </div>
                <!-- Image preview field -->

                @*<img id="imagePreview" style="max-height: 300px; max-width: 300px; display: none;"/>*@

            </div>
        </div>
        <br/>
        <div class="d-grid pb-3">
            <div class="btn-group" role="group">
                <button type="submit" class="btn btn-dark btn-outline-dark text-white btn-lg extra-button-style-b" style="width: 150px">Oppdater</button>
                <a asp-controller="Justdoit" asp-action="Index" class="btn btn-light btn-outline-dark btn-lg extra-button-style" style="width: 150px">Tilbake</a>
            </div>
        </div>
    </div>
</form>


<!--This script makes sure that the validation process is done on client-side instead of server-side-->

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
	
    <script src="~/js/createSuggestion.js"></script>

}
    @*
    This script is used to count the remaining characters in the create suggestion form for the "title" and "description" fields.
    The function will count backwards from the fields' maximum value until it reaches zero.
*@
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById('Title').onkeyup = function () {
                document.getElementById('countCharTitle').innerHTML = (30 - this.value.length) + "/30";
            };
        });

        document.addEventListener("DOMContentLoaded", function () {
            document.getElementById('Description').onkeyup = function () {
                document.getElementById('countCharDesc').innerHTML = (500 - this.value.length) + "/500";
            };
        });
    </script>